name: "Home Inventory"
description: "Tracks supplies, capable of setting quantity to keep track of items."
version: "1.5.2"
slug: "home_inventory"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - share:rw
options:
  port: 8099
schema:
  port: int
ports:
  8099/tcp: 8099
webui: "http://[HOST]:[PORT:8099]/"
ingress: true
ingress_port: 8099
ingress_stream: true
